repos:
-   repo: local
    hooks:
    -   id: update-years
        name: Update year references
        entry: ./update_years.py
        language: system
        always_run: true
        pass_filenames: false
