name: 💡 Feature Request
description: Suggest an idea or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡
        Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternative approaches could be..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Image Processing (new formats, algorithms)
        - User Interface (terminal UI improvements)
        - Performance (speed, memory optimization)
        - Configuration (settings, customization)
        - Integration (other tools, cloud services)
        - Documentation (help, tutorials)
        - Development (testing, build tools)
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would be helpful)
        - High (needed for my workflow)
        - Critical (blocking my usage)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        - Who would benefit from this feature?
        - In what scenarios would it be used?
        - How often would you use it?
    validations:
      required: true

  - type: textarea
    id: mockup
    attributes:
      label: Mockup/Example
      description: If applicable, add mockups, screenshots, or examples
      placeholder: |
        You can drag and drop images here or provide text examples:

        Example terminal output:
        ```
        New Feature: Batch Resize
        Enter target size: 1920x1080
        ```

  - type: input
    id: similar-tools
    attributes:
      label: Similar Tools
      description: Are there other tools that have this feature?
      placeholder: "Tool X has a similar feature where..."

  - type: dropdown
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Would you be willing to help implement this feature?
      options:
        - "Yes, I can implement it myself"
        - "Yes, I can help with testing"
        - "Yes, I can help with documentation"
        - "I'd like to help but need guidance"
        - "I can only provide feedback"

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for this feature
          required: true
        - label: This feature would benefit multiple users, not just my specific use case
          required: true
        - label: I understand this is a volunteer-driven project with no guarantees of implementation
          required: true